name: Build and Deploy Svelte App
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.19.1 # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Svelte app
        run: npm run build

      - name: Create Docs folder
        run: mkdir docs

      - name: Copy built files to Docs folder
        run: cp -R build/* docs/
      - name: Clear Git Credentials
        run: git credential-cache exit

      - name: Commit and push changes
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Build and deploy Svelte app"
            git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}